apiVersion: v1
kind: ServiceAccount
metadata:
  name: quarkus-app
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: quarkus-secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: quarkus-secret-reader-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: quarkus-app
    namespace: default
roleRef:
  kind: Role
  name: quarkus-secret-reader
  apiGroup: rbac.authorization.k8s.io
