apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-api
  template:
    metadata:
      labels:
        app: content-api
    spec:
      containers:
        - image: ghcr.io/fontys-lunarflow/content_api:latest
          imagePullPolicy: Always
          name: content-api
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: content-api
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: content-api
  type: ClusterIP
